use gamelog;

ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_GAMELOG; 
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TEAM;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_PITCH;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_BAT;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_DEFENSE;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_LINEITEM_POS;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_LINEITEM_ORDER;
ALTER TABLE TM_GAMELINE_PITCH DROP FOREIGN KEY  FK_TM_GAMELINE_PITCH_TM_GAMELOG;
ALTER TABLE TM_GAMELINE_BAT DROP FOREIGN KEY  FK_TM_GAMELINE_BAT_TM_GAMELOG;
ALTER TABLE TM_GAMELINE_DEFENSE DROP FOREIGN KEY  FK_TM_GAMELINE_DEFENSE_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_1_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_2_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_3_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_4_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_5_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_6_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_7_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_8_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_9_TM_GAMELOG;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_TM_GAMELOG;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_MANAGER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_PITCHER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_CATCHER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_FIRSTBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_SECONDBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_THIRDBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_SHORTSTOP_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_LEFT_FIELD_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_CENTER_FIELD_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_RIGHT_FIELD_PERSON;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_SEASON;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_TM_GAMELOG_HOME;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_TM_GAMELOG_VISITOR;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_UMP_GAMELOG;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PARK;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_WP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_LP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_SP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_GWRBI;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_GAMETYPE;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_WEEKDAY;

delete from lineitem_order;
delete from lineitem_pos;
delete from tm_gameline_bat;
delete from tm_gameline_pitch;
delete from tm_gameline_defense;
delete from tm_gamelog;
delete from gamelog;





