use gamelog;

ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_GAMELOG; 
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TEAM;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_PITCH;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_BAT;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_GAMELINE_DEFENSE;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_LINEITEM_POS;
ALTER TABLE TM_GAMELOG DROP FOREIGN KEY  FK_TM_GAMELOG_TM_LINEITEM_ORDER;
ALTER TABLE TM_GAMELINE_PITCH DROP FOREIGN KEY  FK_TM_GAMELINE_PITCH_TM_GAMELOG;
ALTER TABLE TM_GAMELINE_BAT DROP FOREIGN KEY  FK_TM_GAMELINE_BAT_TM_GAMELOG;
ALTER TABLE TM_GAMELINE_DEFENSE DROP FOREIGN KEY  FK_TM_GAMELINE_DEFENSE_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_1_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_2_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_3_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_4_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_5_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_6_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_7_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_8_TM_GAMELOG;
ALTER TABLE LINEITEM_ORDER DROP FOREIGN KEY  FK_TM_LINEITEM_ORDER_9_TM_GAMELOG;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_TM_GAMELOG;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_MANAGER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_PITCHER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_CATCHER_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_FIRSTBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_SECONDBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_THIRDBASE_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_SHORTSTOP_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_LEFT_FIELD_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_CENTER_FIELD_PERSON;
ALTER TABLE LINEITEM_POS DROP FOREIGN KEY FK_TM_LINEITEM_POS_RIGHT_FIELD_PERSON;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_SEASON;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_TM_GAMELOG_HOME;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_TM_GAMELOG_VISITOR;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_UMP_GAMELOG;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PARK;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_WP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_LP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_SP;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_PERSON_GWRBI;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_GAMETYPE;
ALTER TABLE GAMELOG DROP FOREIGN KEY FK_GAMELOG_WEEKDAY;

ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_GAMELOG;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_HP_PERSON;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_FB_PERSON;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_SB_PERSON;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_TB_PERSON;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_LF_PERSON;
ALTER TABLE UMP_GAMELOG DROP FOREIGN KEY FK_UMP_GAMELOG_RF_PERSON;

delete from lineitem_order;
delete from lineitem_pos;
delete from tm_gameline_bat;
delete from tm_gameline_pitch;
delete from tm_gameline_defense;
delete from tm_gamelog;
delete from gamelog;

ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_TM_GAMELOG_HOME
	foreign key (TM_GAMELOG_HOME_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_TM_GAMELOG_VISITOR
	foreign key (TM_GAMELOG_VISITOR_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_UMP_GAMELOG
	foreign key (UMP_GAMELOG_ID_FK)
	references UMP_GAMELOG(UMP_GAMELOG_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_PARK
	foreign key (PARK_ID_FK)
	references PARK(PARK_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_PERSON_WP
	foreign key (WP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_PERSON_LP
	foreign key (LP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_PERSON_SP
	foreign key (SP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_PERSON_GWRBI
	foreign key (GWRBI_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_GAMETYPE
	foreign key (GAMETYPE_ID_FK)
	references GAMETYPE(GAMETYPE_CODE);

ALTER TABLE GAMELOG ADD constraint FK_GAMELOG_WEEKDAY
	foreign key (DAY_OF_WEEK_FK)
	references WEEKDAY(WEEKDAY_CODE);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_GAMELOG
	foreign key (GAMELOG_ID_FK)
	references GAMELOG(GAMELOG_ID_PK);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TEAM
	foreign key (TEAM_ID_FK)
	references TEAM(TEAM_ID_PK);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TM_GAMELINE_PITCH
	foreign key (TM_GAMELINE_PITCH_ID_FK)
	references TM_GAMELINE_PITCH(TM_GAMELINE_PITCH_ID_PK);
	
ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TM_GAMELINE_BAT
	foreign key (TM_GAMELINE_BAT_ID_FK)
	references TM_GAMELINE_BAT(TM_GAMELINE_BAT_ID_PK);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TM_GAMELINE_DEFENSE
	foreign key (TM_GAMELINE_DEFENSE_ID_FK)
	references TM_GAMELINE_DEFENSE(TM_GAMELINE_DEFENSE_ID_PK);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TM_LINEITEM_POS
	foreign key (TM_LINE_ITEM_POS_ID_FK)
	references LINEITEM_POS(TM_LINE_ITEM_POS_ID_PK);

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELOG_TM_LINEITEM_ORDER
	foreign key (TM_LINE_ITEM_ORDER_ID_FK)
	references LINEITEM_ORDER(TM_LINE_ITEM_ORDER_ID_PK);

ALTER TABLE TM_GAMELINE_PITCH ADD constraint FK_TM_GAMELINE_PITCH_TM_GAMELOG
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

ALTER TABLE TM_GAMELINE_BAT ADD constraint FK_TM_GAMELINE_BAT_TM_GAMELOG
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

ALTER TABLE TM_GAMELINE_DEFENSE ADD constraint FK_TM_GAMELINE_DEFENSE_TM_GAMELOG
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);


ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_TM_GAMELOG
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_1_TM_GAMELOG
	foreign key (ORDER_1_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_2_TM_GAMELOG
	foreign key (ORDER_2_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_3_TM_GAMELOG
	foreign key (ORDER_3_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_4_TM_GAMELOG
	foreign key (ORDER_4_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_5_TM_GAMELOG
	foreign key (ORDER_5_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_6_TM_GAMELOG
	foreign key (ORDER_6_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_7_TM_GAMELOG
	foreign key (ORDER_7_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_8_TM_GAMELOG
	foreign key (ORDER_8_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_LINEITEM_ORDER_9_TM_GAMELOG
	foreign key (ORDER_9_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_TM_GAMELOG
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_MANAGER_PERSON
	foreign key (POS_MANAGER_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_PITCHER_PERSON
	foreign key (POS_PITCHER_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_CATCHER_PERSON
	foreign key (POS_CATCHER_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_FIRSTBASE_PERSON
	foreign key (POS_FIRSTBASE_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_SECONDBASE_PERSON
	foreign key (POS_SECONDBASE_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_THIRDBASE_PERSON
	foreign key (POS_THIRDBASE_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_SHORTSTOP_PERSON
	foreign key (POS_SHORTSTOP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_LEFT_FIELD_PERSON
	foreign key (POS_LEFT_FIELD_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_CENTER_FIELD_PERSON
	foreign key (POS_CENTER_FIELD_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE LINEITEM_POS ADD constraint FK_TM_LINEITEM_POS_RIGHT_FIELD_PERSON
	foreign key (POS_RIGHT_FIELD_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_GAMELOG
	foreign key (GAMELOG_ID_FK)
	references GAMELOG(GAMELOG_ID_PK);
	
ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_HP_PERSON
	foreign key (HP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_FB_PERSON
	foreign key (FB_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_SB_PERSON
	foreign key (SB_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_TB_PERSON
	foreign key (TB_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_LF_PERSON
	foreign key (LF_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
	
ALTER TABLE UMP_GAMELOG ADD constraint FK_UMP_GAMELOG_RF_PERSON
	foreign key (RF_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);





