-- works.
ALTER TABLE GAMELOG ADD constraint FK_SEASON 
	foreign key (SEASON_ID_FK) 
	references SEASON(SEASON_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_GAMETYPE 
	foreign key (GAMETYPE_ID_FK) 
	references GAMETYPE(GAME_TYPE_CODE);	
	
ALTER TABLE GAMELOG ADD constraint FK_DAY_OF_WEEK
	foreign key (DAY_OF_WEEK_FK) 
	references WEEKDAY(WEEK_DAY_CODE);
	
ALTER TABLE GAMELOG ADD constraint FK_PARK
	foreign key (PARK_ID_FK)
	references PARK(PARK_ID_PK);
	
ALTER TABLE GAMELOG ADD constraint FK_WP_PERSON
	foreign key (WP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);

ALTER TABLE GAMELOG ADD constraint FK_LP_PERSON
	foreign key (LP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);
    
ALTER TABLE GAMELOG ADD constraint FK_SP_PERSON
	foreign key (SP_PERSON_ID_FK)
	references PERSON(PERSON_ID_PK);    

ALTER TABLE GAMELOG ADD constraint FK_GW_RBI_PERSON  
	foreign key (GW_RBI_PERSONID_FK)  
	references PERSON(PERSON_ID_PK);

ALTER TABLE GAMELOG ADD constraint FK_UMP_GAMELOG
	foreign key (UMP_GAMELOG_ID_FK)
	references UMP_GAMELOG(UMP_GAMELOG_ID_PK);
    
ALTER TABLE GAMELOG ADD constraint FK_TM_GAMELOG_H
	foreign key (H_TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

ALTER TABLE GAMELOG ADD constraint FK_TM_GAMELOG_V
	foreign key (V_TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

 ALTER TABLE TM_GAMELOG MODIFY COLUMN TEAM_ID_FK bigint(20);
	
ALTER TABLE TM_GAMELOG ADD constraint FK_TEAM	
	foreign key (TEAM_ID_FK)
	references TEAM(TEAM_ID_PK);
    
ALTER TABLE TM_GAMELOG MODIFY COLUMN TM_GAMELINE_PITCH_ID_FK bigint(20) unsigned;

ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELINE_PITCH	
	foreign key (TM_GAMELINE_PITCH_ID_FK)
	references TM_GAMELINE_PITCH(TM_GAMELINE_PITCH_ID_PK);
    
ALTER TABLE TM_GAMELOG MODIFY COLUMN TM_GAMELINE_BAT_ID_FK bigint(20) unsigned;
		
ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELINE_BAT	
	foreign key (TM_GAMELINE_BAT_ID_FK)
	references TM_GAMELINE_BAT(TM_GAMELINE_BAT_ID_PK);
    
ALTER TABLE TM_GAMELOG MODIFY COLUMN TM_GAMELINE_DEFENSE_ID_FK bigint(20);
	
ALTER TABLE TM_GAMELOG ADD constraint FK_TM_GAMELINE_DEFENSE	
	foreign key (TM_GAMELINE_DEFENSE_ID_FK)
	references TM_GAMELINE_DEFENSE(TM_GAMELINE_DEFENSE_ID_PK);
    
ALTER TABLE TM_GAMELOG MODIFY COLUMN TM_LINE_ITEM_POS_ID_FK bigint(20) unsigned;
	
ALTER TABLE TM_GAMELOG ADD constraint FK_TM_LINE_ITEM_POS	
	foreign key (TM_LINE_ITEM_POS_ID_FK)
	references LINEITEM_POS(TM_LINE_ITEM_POS_ID_PK);
    

ALTER TABLE TM_GAMELOG MODIFY COLUMN TM_LINE_ITEM_ORDER_ID_FK bigint(20) unsigned;

	
ALTER TABLE TM_GAMELOG ADD constraint FK_TM_LINE_ITEM_ORDER	
	foreign key (TM_LINE_ITEM_ORDER_ID_FK)
	references LINEITEM_ORDER(TM_LINE_ITEM_ORDER_ID_PK);
ALTER TABLE LINEITEM_ORDER MODIFY COLUMN TM_GAMELOG_ID_FK bigint(20) unsigned;

ALTER TABLE LINEITEM_ORDER ADD constraint FK_TM_GAMELOG_FOR_ORDER	
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);

ALTER TABLE LINEITEM_POS MODIFY COLUMN TM_GAMELOG_ID_FK bigint(20) unsigned;

 	
ALTER TABLE LINEITEM_POS ADD constraint FK_TM_GAMELOG_FOR_POS	
	foreign key (TM_GAMELOG_ID_FK)
	references TM_GAMELOG(TM_GAMELOG_ID_PK);    
   