-- A Comprehensive Guide to Using MySQL ENUM: http://www.mysqltutorial.org/mysql-enum/
-- based on recommendations, do not create tables with enum columns.alter
-- ref: https://www.w3schools.com/sql/sql_foreignkey.asp
-- ref: https://www.w3schools.com/sql/sql_foreignkey.asp

create table LOCATION (
	LOCATION_ID_PK bigint UNSIGNED not null auto_increment,
    COUNTRY varchar(25),
    COUNTRY_CODE varchar (6),
    STATE varchar (30),
    STATE_CODE varchar (6),
    CITY varchar (20),
    VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(LOCATION_ID_PK)
    )engine=InnoDB;

create table PARK  (
	PARK_ID_PK bigint UNSIGNED not null auto_increment,
	LOCATION_ID_FK bigint UNSIGNED not null,
    PARK_CODE char(5) not null,
    NAME varchar(45) not null,
    ALIAS varchar(45),
    START date,
    END date,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(PARK_ID_PK),
    unique(PARK_CODE),
    constraint FK_PARK_LOCATION foreign key (LOCATION_ID_FK) references LOCATION(LOCATION_ID_PK)
    )engine=InnoDB;

create table if not exists DIVISION (
	DIVISION_ID_PK int UNSIGNED not null auto_increment,
    DIVISION_CODE char(1) not null,
    NAME varchar(10),
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(DIVISION_ID_PK),
    unique(DIVISION_CODE)
)engine=InnoDB;

create table if not exists LEAGUE (
	LEAGUE_ID_PK int UNSIGNED not null auto_increment,
    DIVISION_ID_FK int UNSIGNED null,
    LEAGUE_CODE char(2) not null,
    NAME varchar(30) not null,
    primary key(LEAGUE_ID_PK),
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    constraint FK_DIVISION foreign key (DIVISION_ID_FK) references DIVISION(DIVISION_ID_PK)
)engine=InnoDB;



create table if not exists SEASON (
	SEASON_ID_PK int UNSIGNED not null auto_increment,
    SEASON_CODE char(4) not null unique,
    SEASON_VALUE int,
    VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(SEASON_ID_PK)  
)engine=InnoDB;

create table if not exists FRANCHISE (
	FRANCHISE_ID_PK int UNSIGNED not null auto_increment,
    FRANCHISE_CODE char(3) not null,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(FRANCHISE_ID_PK),
    unique(FRANCHISE_CODE)
)engine=InnoDB;

create table if not exists TEAM (
	TEAM_ID_PK bigint UNSIGNED not null auto_increment,
    FRANCHISE_ID_FK int UNSIGNED not null,
    LEAGUE_ID_FK int UNSIGNED not null,
    LOCATION_ID_FK bigint UNSIGNED not null,
    SEASON_ID_FK int UNSIGNED not null,
    TEAM_CODE char(4) unique,
    NAME varchar(30),
    ALIAS varchar(30),
    VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(TEAM_ID_PK)
 )engine=InnoDB;   

--- PERSON Stuff

create table if not exists PERSON(
	PERSON_ID_PK bigint UNSIGNED not null auto_increment,
	LOCATION_ID_FK bigint UNSIGNED,
    PERSON_CODE  varchar(15) not null unique,
    FULL_NAME varchar(92) not null,
    LAST_NAME varchar(30),
    MIDDLE_NAME varchar (30),
    FIRST_NAME varchar(30),
    NICK_NAME varchar(30),
    OKA varchar(200),
    BATS char(1),
    THROWS char(1),
    HEIGHT tinyint(2) UNSIGNED,
    WEIGHT smallint(3) UNSIGNED,
    DATE_OF_BIRTH DATE,
	DATE_OF_DEATH DATE,
	DATE_OF_DEBUT_COACH DATE, 
	DATE_OF_DEBUT_MANAGER DATE,
	DATE_OF_DEBUT_PLAYER DATE,
	DATE_OF_DEBUT_UMPIRE DATE,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	primary key (PERSON_ID_PK)
)engine=InnoDB;


CREATE TABLE if not exists GAMELOG(
	GAMELOG_ID_PK bigint UNSIGNED not null auto_increment,
	GAMELOG_CODE varchar(11),
	SEASON_ID_FK int UNSIGNED not null,
	TM_GAMELOG_HOME_FK bigint UNSIGNED,
	TM_GAMELOG_VISITOR_FK bigint UNSIGNED,
	UMP_GAMELOG_ID_FK bigint UNSIGNED,
	PARK_ID_FK bigint UNSIGNED not null,
	WP_PERSON_ID_FK bigint UNSIGNED,
	LP_PERSON_ID_FK bigint UNSIGNED,
	SP_PERSON_ID_FK bigint UNSIGNED,
	GWRBI_PERSON_ID_FK bigint UNSIGNED,
	GAMETYPE_ID_FK  varchar(3) not null,
	DAY_OF_WEEK_FK varchar(2) not null,
	DATE_OF_GAME DATE,
	DAY_GAME BOOLEAN,
	ATTENDANCE smallint(7) UNSIGNED,
	TIME_OF_GAME smallint(3) UNSIGNED,
	V_TM_GAME_SCORE varchar(50),
	H_TM_GAME_SCORE varchar(50),
	V_SCORE tinyint(2) UNSIGNED,
	H_SCORE tinyint(2) UNSIGNED,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (GAMELOG_ID_PK)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists GAMETYPE(
	GAMETYPE_CODE varchar(3) not null unique,
	GAMETYPE_DESC varchar(75) not null unique,
 	CREATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	primary key (GAMETYPE_CODE)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;


CREATE TABLE if not exists WEEKDAY(
    WEEKDAY_CODE varchar(3) not null unique,
    WEEKDAY_NUM tinyint(1) UNSIGNED not null unique,
 	CREATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	primary key (WEEKDAY_CODE )
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;


CREATE TABLE if not exists TM_GAMELOG(
	TM_GAMELOG_ID_PK bigint UNSIGNED not null auto_increment,
	GAMELOG_ID_FK bigint UNSIGNED not null,
	TEAM_ID_FK bigint UNSIGNED not null,
	TM_GAMELINE_PITCH_ID_FK bigint UNSIGNED,
	TM_GAMELINE_BAT_ID_FK bigint UNSIGNED,
	TM_GAMELINE_DEFENSE_ID_FK bigint UNSIGNED,
	TM_LINE_ITEM_POS_ID_FK bigint UNSIGNED,
	TM_LINE_ITEM_ORDER_ID_FK bigint UNSIGNED,
	HOME_AWAY_CODE char(1) not null,  
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (TM_GAMELOG_ID_PK)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists TM_GAMELINE_PITCH(
	TM_GAMELINE_PITCH_ID_PK bigint UNSIGNED not null auto_increment,
	TM_GAMELOG_ID_FK  bigint UNSIGNED not null,
	PITCHERS_USED tinyint UNSIGNED,
	INDIVIDUAL_ER tinyint UNSIGNED,
	TEAM_ER tinyint UNSIGNED,
	WP tinyint UNSIGNED,
	BALKS tinyint UNSIGNED,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (TM_GAMELINE_PITCH_ID_PK)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists TM_GAMELINE_BAT(
	TM_GAMELINE_BAT_ID_PK bigint UNSIGNED not null auto_increment,
	TM_GAMELOG_ID_FK  bigint UNSIGNED not null,
	AB tinyint UNSIGNED DEFAULT 0,
	H tinyint UNSIGNED DEFAULT 0,
	D tinyint UNSIGNED DEFAULT 0,
	T tinyint UNSIGNED DEFAULT 0,
	HR tinyint UNSIGNED DEFAULT 0,
	RBI tinyint UNSIGNED DEFAULT 0,
	SH tinyint UNSIGNED DEFAULT 0,
	SF tinyint UNSIGNED DEFAULT 0,
	HBP tinyint UNSIGNED DEFAULT 0,
	BB tinyint UNSIGNED DEFAULT 0,
	IBB tinyint UNSIGNED DEFAULT 0,
	SO tinyint UNSIGNED DEFAULT 0,
	SB tinyint UNSIGNED DEFAULT 0,
	CS tinyint UNSIGNED DEFAULT 0,
	GIDP tinyint UNSIGNED DEFAULT 0,
	AWCI tinyint UNSIGNED DEFAULT 0,
	LOB tinyint UNSIGNED DEFAULT 0,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (TM_GAMELINE_BAT_ID_PK)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists TM_GAMELINE_DEFENSE(
	TM_GAMELINE_DEFENSE_ID_PK bigint UNSIGNED not null auto_increment,
	TM_GAMELOG_ID_FK  bigint UNSIGNED not null,
	PUTOUTS tinyint DEFAULT 0,
	ASSISTS tinyint DEFAULT 0,
	ERRORS tinyint DEFAULT 0,
	PB tinyint DEFAULT 0,
	DP tinyint DEFAULT 0,
	TP tinyint DEFAULT 0,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (TM_GAMELINE_DEFENSE_ID_PK)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists LINEITEM_ORDER(
	TM_LINE_ITEM_ORDER_ID_PK bigint UNSIGNED not null auto_increment,
	TM_GAMELOG_ID_FK  bigint UNSIGNED not null,
	ORDER_1_PERSON_ID_FK bigint UNSIGNED,
	ORDER_2_PERSON_ID_FK bigint UNSIGNED,
	ORDER_3_PERSON_ID_FK bigint UNSIGNED,
	ORDER_4_PERSON_ID_FK bigint UNSIGNED,
	ORDER_5_PERSON_ID_FK bigint UNSIGNED,
	ORDER_6_PERSON_ID_FK bigint UNSIGNED,
	ORDER_7_PERSON_ID_FK bigint UNSIGNED,
	ORDER_8_PERSON_ID_FK bigint UNSIGNED,
	ORDER_9_PERSON_ID_FK bigint UNSIGNED,
		VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (TM_LINE_ITEM_ORDER_ID_PK)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists LINEITEM_POS(
	TM_LINE_ITEM_POS_ID_PK bigint UNSIGNED not null auto_increment,
	TM_GAMELOG_ID_FK  bigint UNSIGNED not null,
	POS_MANAGER_PERSON_ID_FK bigint UNSIGNED,
	POS_PITCHER_PERSON_ID_FK bigint UNSIGNED,
	POS_CATCHER_PERSON_ID_FK bigint UNSIGNED,
	POS_FIRSTBASE_PERSON_ID_FK bigint UNSIGNED,
	POS_SECONDBASE_PERSON_ID_FK bigint UNSIGNED,
	POS_THIRDBASE_PERSON_ID_FK bigint UNSIGNED,
	POS_SHORTSTOP_PERSON_ID_FK bigint UNSIGNED,
	POS_LEFT_FIELD_PERSON_ID_FK bigint UNSIGNED,
	POS_CENTER_FIELD_PERSON_ID_FK bigint UNSIGNED,
	POS_RIGHT_FIELD_PERSON_ID_FK bigint UNSIGNED,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (TM_LINE_ITEM_POS_ID_PK)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE if not exists UMP_GAMELOG(
	UMP_GAMELOG_ID_PK bigint UNSIGNED not null auto_increment,
	GAMELOG_ID_FK bigint UNSIGNED,
	HP_PERSON_ID_FK bigint UNSIGNED,
	FB_PERSON_ID_FK bigint UNSIGNED,
	SB_PERSON_ID_FK bigint UNSIGNED,
	TB_PERSON_ID_FK bigint UNSIGNED,
	LF_PERSON_ID_FK bigint UNSIGNED,
	RF_PERSON_ID_FK bigint UNSIGNED,
	VERSION int(11) DEFAULT '0',
  	CREATED_BY varchar(255) DEFAULT 'FLYWAY' ,
  	DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	UPDATED_BY varchar(255) DEFAULT 'FLYWAY',
  	DATE_UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (UMP_GAMELOG_ID_PK)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;
	
--CREATE TABLE `Cart` (
--  `cart_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
--  PRIMARY KEY (`cart_id`)
--) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4;
 
--CREATE TABLE `Items` (
--  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
--  `cart_id` int(11) unsigned NOT NULL,
--  PRIMARY KEY (`id`),
--  KEY `cart_id` (`cart_id`),
--  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`cart_id`) REFERENCES `Cart` (`cart_id`)
--) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=UTF8MB4;
